---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstmicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: firstmicroservice
    spec:
      containers:
        - name: firstmicroservice
          image: viktorija11/firstmicroservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: firstmicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: firstmicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: firstmicroservice
